### ISSUE TITLE
Can't install it

### ISSUE THREAD

**Issue by cgotelli** [VeinsOfTheEarth/RivGraph#83]
Hello!
I have been trying to install with the different methods proposed in the [website](https://veinsoftheearth.github.io/RivGraph/install/index.html#installation-from-source). However, it is forever processing without installing. Is it necessary a specific Conda version? I could not find any information about it. I also tried with a fresh installation of Anaconda and Miniconda, but it did not work 😭.
Thanks in advance for your help.

**Comment by elbeejay** [comment]
Hi @cgotelli - dependency resolution has definitely been an ongoing challenge with RivGraph, so your problem is understandable. I do not believe a specific conda version is needed at this time, however I'd check the version of Python you are trying to install RivGraph into. At this time we haven't explicitly tested Python 3.10, but 3.9 should be working, and I've just gotten it to install via the `conda` instructions in a Google Colab notebook which is running Python 3.7.13. 

To speed up the dependency resolution and installation processing, I would suggest trying [mamba](https://mamba.readthedocs.io/en/latest/index.html) as an alternative to `conda`. The installation instructions will be the same, you'd just replace the word `conda` with `mamba` in each line. In the Colab notebook, I was able to install RivGraph with the command `!mamba install rivgraph -c conda-forge` in about 1 minute. 

Hopefully that is helpful; if you still have trouble please provide a bit more context about your specific setup (Python version, operating system, etc.)

**Comment by cgotelli** [comment]
Thank you for your answer @elbeejay! I was able to install it in Colab, just like you did. So I tried to replicate the process, using also Python 3.7.13 in different pcs, environments, OS, etc. with no success. No clue about what is wrong, I tried all the possible alternatives I could find in internet to fix the endless `Solving environment: failed with initial frozen solve.` but nothing worked. I was not even able to install mamba using conda-forge, and I had to install it with [mamba-forge](https://github.com/conda-forge/miniforge#mambaforge). Luckily, after doing that, it worked. 
This situation is very strange. Not long ago I installed Rivgraph with no problems in the same pc, but after I had to format it, I could not make it work. I think the alternative you give is very useful and it would be good to have it in the documentation for future people like me.   
Thanks again for your help. I will try to give Rivgraph a good use!

**Comment by jonschwenk** [comment]
Closing. Thanks @elbeejay. One thing worth noting is that we migrated the rivgraph package to conda-forge (away from jschwenk) a couple of weeks ago, so make sure to pull from the conda-forge channel (as it's still available via jschwenk).
